name = "FiniteVolumeMethod1D"
uuid = "cfdabe9e-7cc8-40e3-9725-d80209c3e763"
authors = ["DanielVandH <danj.vandenheuvel@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
